# Use a versão oficial do Node.js como base
FROM node:20.15.1

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Copie o package.json e package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código-fonte
COPY . .

# Construa o projeto
RUN npm run build

# Exponha a porta que o Vite usa por padrão
EXPOSE 5173

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "dev"]
