# Dockerfile for backend
FROM node:20.15.1

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source code
COPY . .

# Build the project
RUN npm run build

# Expose port
EXPOSE 3000

# Command to run the app
CMD ["npm", "start"]
